// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Test_Task.Helpers;

namespace Test_Task.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20201221111407_NewTables")]
    partial class NewTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Test_Task.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("NumberOfPages")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NumberOfPages = 432,
                            Title = "Kobzar"
                        });
                });

            modelBuilder.Entity("Test_Task.Models.Phone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ManufacturerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Phones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ManufacturerName = "Apple",
                            Model = "Iphone 7"
                        },
                        new
                        {
                            Id = 2,
                            ManufacturerName = "Samsung",
                            Model = "Galaxy S8"
                        });
                });

            modelBuilder.Entity("Test_Task.Models.Table", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tables");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Height = 140,
                            Name = "Drawing table"
                        });
                });

            modelBuilder.Entity("Test_Task.Models.Tree", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Kind")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Trees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 73,
                            Kind = "Oak"
                        },
                        new
                        {
                            Id = 2,
                            Age = 37,
                            Kind = "Birch"
                        });
                });

            modelBuilder.Entity("Test_Task.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 22,
                            Name = "Vadym"
                        },
                        new
                        {
                            Id = 2,
                            Age = 21,
                            Name = "Vova"
                        },
                        new
                        {
                            Id = 3,
                            Age = 25,
                            Name = "Kolia"
                        },
                        new
                        {
                            Id = 4,
                            Age = 22,
                            Name = "Vika"
                        },
                        new
                        {
                            Id = 5,
                            Age = 20,
                            Name = "Nastia"
                        });
                });

            modelBuilder.Entity("Test_Task.Models.Window", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Windows");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Height = 180,
                            Width = 200
                        },
                        new
                        {
                            Id = 2,
                            Height = 190,
                            Width = 210
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
