// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Test_Task.Helpers;

namespace Test_Task.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20201208105456_CreateDataBase")]
    partial class CreateDataBase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Test_Task.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 22,
                            Name = "Vadym"
                        },
                        new
                        {
                            Id = 2,
                            Age = 21,
                            Name = "Vova"
                        },
                        new
                        {
                            Id = 3,
                            Age = 25,
                            Name = "Kolia"
                        },
                        new
                        {
                            Id = 4,
                            Age = 22,
                            Name = "Vika"
                        },
                        new
                        {
                            Id = 5,
                            Age = 20,
                            Name = "Nastia"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
